Repository home-assistant/cli, pull requests merged in 2018-02, with the labels that each got.

#48 Bugfix arm builds
  .travis.yml
Labels: cla-signed

#49 Release 1.1.2
  .travis.yml
  version.go
Labels: cla-signed

#50 Merge Master back into dev
  version.go
Labels: cla-signed

#53 Tidied output when error is detected
  command/helpers/common.go
Labels: Breaking Change, cla-signed

#55 Standardised Short names for commands
  commands.go
Labels: Breaking Change, cla-signed, enhancement

#57 Release 1.2
  command/helpers/common.go
  commands.go
  version.go
Labels: cla-signed

#58 Master
  version.go
Labels: cla-signed

#59 Release 1.2.1
  command/helpers/common.go
  version.go
Labels: cla-signed

#60 Master merge back
  version.go
Labels: cla-signed
