Repository home-assistant/cli, pull requests merged in 2018-11, with the labels that each got.

#126 Fix travis issues and resulting golint errors
  .travis.yml
  command/helpers/common.go
  command/helpers/common_test.go
Labels: cla-signed, enhancement

#120 Comment spelling fix
  commands.go
Labels: Hacktoberfest, cla-signed

#124 Remove unnecessary comments from tests file
  command/helpers/common_test.go
Labels: cla-signed
