Repository home-assistant/cli, pull requests merged in 2019-08, with the labels that each got.

#164 merging Dev into master
  .travis.yml
  README.md
  go.mod
  go.sum
Labels: cla-signed

#165 Removes duplicate env setting in TravisCI file
  .travis.yml
Labels: cla-signed

#166 Only set add-on repositories when at least 1 is given
  cmd/supervisor_options.go
Labels: cla-signed

#168 Adds VSCode remote devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: cla-signed, enhancement

#169 Adds support for generating ZSH completion script
  cmd/completion.go
Labels: cla-signed, enhancement

#167 Adds support for DNS commands
  cmd/dns.go
  cmd/dns_info.go
  cmd/dns_logs.go
  cmd/dns_options.go
  cmd/dns_stats.go
  cmd/dns_update.go
Labels: cla-signed, enhancement

#171 Removes addons logo & icons commands
  cmd/addons_icon.go
  cmd/addons_logo.go
Labels: cla-signed

#172 Improves command documentation and aliases
  cmd/addons.go
  cmd/addons_changelog.go
  cmd/addons_info.go
  cmd/addons_install.go
  cmd/addons_logs.go
  cmd/addons_rebuild.go
  cmd/addons_reload.go
  cmd/addons_restart.go
  cmd/addons_start.go
  cmd/addons_stats.go
  cmd/addons_stop.go
  cmd/addons_uninstall.go
  cmd/addons_update.go
  cmd/completion.go
  cmd/dns.go
  cmd/dns_info.go
  cmd/dns_logs.go
  cmd/dns_options.go
  cmd/dns_stats.go
  cmd/dns_update.go
  cmd/hardware.go
  cmd/hardware_audio.go
  cmd/hardware_info.go
  cmd/hassos.go
  cmd/hassos_import.go
  cmd/hassos_info.go
  cmd/hassos_update.go
  cmd/hassos_update_cli.go
  cmd/homeassistant.go
  cmd/homeassistant_check.go
  cmd/homeassistant_info.go
  cmd/homeassistant_logs.go
  cmd/homeassistant_options.go
  cmd/homeassistant_rebuild.go
  cmd/homeassistant_restart.go
  cmd/homeassistant_start.go
  cmd/homeassistant_stop.go
  cmd/homeassistant_update.go
  cmd/host.go
  cmd/host_info.go
  cmd/host_options.go
  cmd/host_reboot.go
  cmd/host_reload.go
  cmd/host_shutdown.go
  cmd/info.go
  cmd/root.go
  cmd/snapshots.go
  cmd/snapshots_info.go
  cmd/snapshots_new.go
  cmd/snapshots_reload.go
  cmd/snapshots_remove.go
  cmd/snapshots_restore.go
  cmd/supervisor.go
  cmd/supervisor_info.go
  cmd/supervisor_logs.go
  cmd/supervisor_options.go
  cmd/supervisor_reload.go
  cmd/supervisor_repair.go
  cmd/supervisor_stats.go
  cmd/supervisor_update.go
Labels: cla-signed

#170 Updates go modules, removes golang 1.11 support
  .travis.yml
  go.mod
  go.sum
Labels: cla-signed

#173 Add homeassistant stats
  cmd/homeassistant_stats.go
Labels: cla-signed

#174 Fixes output of numbers, upgrades Resty v2
  client/client.go
  client/helper.go
  cmd/addons_info.go
  cmd/addons_install.go
  cmd/addons_rebuild.go
  cmd/addons_restart.go
  cmd/addons_start.go
  cmd/addons_stats.go
  cmd/addons_stop.go
  cmd/addons_uninstall.go
  cmd/addons_update.go
  cmd/info.go
  cmd/snapshots_info.go
  cmd/snapshots_remove.go
  cmd/snapshots_restore.go
  go.mod
  go.sum
Labels: bug, cla-signed

#176 Fixes some typos in CLI help
  cmd/dns.go
Labels: cla-signed

#177 Adds backup as alias to snapshots
  cmd/snapshots.go
Labels: cla-signed

#175 Adds processing spinner and improves command completed message
  client/helper.go
  cmd/addons_install.go
  cmd/addons_rebuild.go
  cmd/addons_reload.go
  cmd/addons_update.go
  cmd/dns_update.go
  cmd/hassos_update.go
  cmd/hassos_update_cli.go
  cmd/homeassistant_check.go
  cmd/homeassistant_rebuild.go
  cmd/homeassistant_restart.go
  cmd/homeassistant_start.go
  cmd/homeassistant_stop.go
  cmd/homeassistant_update.go
  cmd/root.go
  cmd/snapshots_new.go
  cmd/snapshots_restore.go
  cmd/supervisor_repair.go
  cmd/supervisor_update.go
  go.mod
  go.sum
Labels: cla-signed

#178 Add dns restart command
  cmd/dns_restart.go
Labels: cla-signed
